#!/usr/bin/env bash
#
# Builds AWSProfiles.app and puts it in ~/Applications.
# Re-run it any time; it replaces the bundle in place.
#
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# /Applications is the folder people mean by "Applications" — the one in the
# Finder sidebar, Launchpad and Spotlight. It is usually writable by an admin
# user without sudo; fall back to ~/Applications when it is not.
if [ -n "${1:-}" ]; then
  INSTALL_DIR="$1"
elif [ -w /Applications ]; then
  INSTALL_DIR="/Applications"
else
  INSTALL_DIR="$HOME/Applications"
fi
# The bundle name is what Spotlight and `open -a` match on, so it carries the
# space: "AWS Profiles.app", not "AWSProfiles.app".
APP_DIR="$INSTALL_DIR/AWS Profiles.app"
PYTHON="${PYTHON:-python3}"
VENV="$PROJECT_DIR/.venv"

echo "==> Setting up the Python environment"
if [ ! -x "$VENV/bin/python" ]; then
  "$PYTHON" -m venv "$VENV"
fi
"$VENV/bin/python" -m pip install --quiet --upgrade pip
"$VENV/bin/python" -m pip install --quiet --require-hashes -r "$PROJECT_DIR/requirements.txt"

echo "==> Running the test suite"
"$VENV/bin/python" -m unittest discover -s "$PROJECT_DIR/tests" 2>&1 | tail -3

VERSION="$("$VENV/bin/python" -c 'import awsprofiles; print(awsprofiles.__version__)')"
BUILD="$(date +%Y%m%d%H%M)"

echo "==> Building $APP_DIR (version $VERSION, build $BUILD)"
# Clear out earlier installs so LaunchServices does not keep offering them.
rm -rf "$APP_DIR" "$INSTALL_DIR/AWSProfiles.app" "$HOME/Applications/AWSProfiles.app"
mkdir -p "$APP_DIR/Contents/MacOS" "$APP_DIR/Contents/Resources"

cat > "$APP_DIR/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>AWS Profiles</string>
  <key>CFBundleDisplayName</key><string>AWS Profiles</string>
  <key>CFBundleIdentifier</key><string>com.adham.awsprofiles</string>
  <key>CFBundleExecutable</key><string>AWSProfiles</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>$VERSION</string>
  <key>CFBundleVersion</key><string>$BUILD</string>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>CFBundleIconFile</key><string>AppIcon</string>
</dict>
</plist>
PLIST

cat > "$APP_DIR/Contents/MacOS/AWSProfiles" <<LAUNCHER
#!/bin/sh
# Generated by install.sh — paths are baked in, so re-run install.sh if you
# move or rename $PROJECT_DIR.
export AWSPROFILES_LAUNCHER="\$0"
export PYTHONPATH="$PROJECT_DIR"
# Launched from Finder there is no terminal to print to, so keep a log.
# Without this a crash just makes the menu bar icon disappear with no trace.
LOG="\$HOME/Library/Logs/AWSProfiles.log"
# The log never holds secrets today; keep it private in case a future
# traceback prints more than expected.
umask 077
mkdir -p "\$(dirname "\$LOG")"
chmod 600 "\$LOG" 2>/dev/null || true
echo "--- started \$(date) ---" >> "\$LOG"
exec "$VENV/bin/python" -u -m awsprofiles >> "\$LOG" 2>&1
LAUNCHER
chmod +x "$APP_DIR/Contents/MacOS/AWSProfiles"

echo "==> Drawing the app icon"
"$VENV/bin/python" "$PROJECT_DIR/make_icon.py" "$APP_DIR/Contents/Resources/AppIcon.icns" > /dev/null

# Clear the quarantine flag so Gatekeeper does not block a locally built app.
xattr -cr "$APP_DIR" 2>/dev/null || true

# Register with LaunchServices so Spotlight, Launchpad and `open -a` find it
# straight away rather than whenever the system next gets round to indexing.
LSREGISTER="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister"
[ -x "$LSREGISTER" ] && "$LSREGISTER" -f "$APP_DIR" 2>/dev/null || true
# lsregister alone does not make Spotlight aware of it; mdimport does.
mdimport "$APP_DIR" 2>/dev/null || true

echo
echo "Installed: $APP_DIR"
echo
echo "Open it any of these ways:"
echo "  • Finder → Applications → AWS Profiles"
echo "  • Spotlight (⌘Space) → \"AWS Profiles\""
echo "  • Launchpad"
echo "  • open -a \"AWS Profiles\""
